### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by hluo421** [BIOGOHITSZ/HNetGO#1]
HNetGO.py代码中下面部分报错，请问是什么原因呢？

` tag = True
    for protein_id in tqdm(range(len(masked))):
        if masked[protein_id]:
            if protein_id in g.edges(etype = 'annotated_by', form = 'all')[0]:
                tag = False
    assert(tag)
    print("build sub_graph succ")
    return g`
Traceback (most recent call last):
  File "HNetGO.py", line 582, in <module>
    main()
  File "HNetGO.py", line 514, in main
    G, graph = build_subgraph(G), G
  File "HNetGO.py", line 203, in build_subgraph
    assert(tag)
AssertionError

**Comment by kioedru** [comment]
我也在这报错了，请问问题解决了吗
